package com.coherentlogic.coherent.datafeed.integration.transformers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.integration.transformer.AbstractPayloadTransformer;

import com.coherentlogic.coherent.datafeed.adapters.StatusResponseAdapter;
import com.coherentlogic.coherent.datafeed.domain.StatusResponse;
import com.reuters.rfa.omm.OMMMsg;
import com.reuters.rfa.session.omm.OMMItemEvent;

/**
 * Transformer that transforms an instance of {@link OMMItemEvent} into an
 * instance of {@link StatusResponse}.
 *
 * Note that status response messages are neither refreshed or updated -- they
 * are just sent (I believe).
 *
 * @todo Rename the ctor/property to the original value as generated by Eclipse
 *  (rfaBeanAdapter) in all classes in this package along with the bean
 *  definitions as well. The reason is that we're wasting time fixing problems
 *  in Spring when it loads the app ctx because the name of these variables in
 *  the ctors is not consistent.
 *
 * @author <a href="mailto:support@coherentlogic.com">Support</a>
 */
public class StatusResponseTransformer
    extends AbstractPayloadTransformer<OMMMsg, StatusResponse> {

    private static final Logger log =
        LoggerFactory.getLogger(StatusResponseTransformer.class);

    private final StatusResponseAdapter statusResponseAdapter;

    public StatusResponseTransformer(
        StatusResponseAdapter statusResponseAdapter
    ) {
        this.statusResponseAdapter = statusResponseAdapter;
    }

    @Override
    protected StatusResponse transformPayload(OMMMsg ommMsg)
        throws Exception {

        log.info("transformPayload: method begins; ommMsg: " + ommMsg);

        StatusResponse result = statusResponseAdapter.adapt(ommMsg);

        log.info("transformPayload: method ends; result: " + result);

        return result;
    }
}
